name: Create Teshine Keystore

on:
  workflow_dispatch:

jobs:
  create-keystore:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Generate Keystore
        env:
          KEYSTORE_PASSWORD: ${{ secrets.TESHINE_KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.TESHINE_KEY_PASSWORD }}
        run: |
          keytool -genkeypair \
            -v \
            -keystore teshine-release.jks \
            -alias teshine \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "$KEYSTORE_PASSWORD" \
            -keypass "$KEY_PASSWORD" \
            -dname "CN=Teshine, OU=Teshine, O=Teshine, L=Baku, ST=Baku, C=AZ"

      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: teshine-release-keystore
          path: teshine-release.jks
